name: movie-recommender
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
    - pandas
    - numpy
    - scikit-learn
    - nltk
    - mlflow>=2.9.0
    - pytest
    - pytest-cov
    - flake8
