name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov flake8
        python -m nltk.downloader punkt
        python -c "import nltk; nltk.download('punkt')"
        
    - name: Create dataset directory and dummy files for testing
      run: |
        mkdir -p dataset
        echo '{"id":1,"title":"Movie 1"}' > dataset/tmdb_5000_movies.csv
        echo '{"title":"Movie 1"}' > dataset/tmdb_5000_credits.csv
        
    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        
    - name: Run tests with pytest
      run: |
        pytest tests/ -v

  build-and-validate:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Verify dataset
      run: |
        ls -l dataset/
        echo "Verifying dataset files exist..."
        test -f dataset/tmdb_5000_movies.csv
        test -f dataset/tmdb_5000_credits.csv
        
    - name: Train and validate model
      run: |
        python movie_recommender.py
        
    - name: Upload MLflow artifacts
      uses: actions/upload-artifact@v2
      with:
        name: mlflow-artifacts
        path: mlruns/

  deploy:
    needs: build-and-validate
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        
    - name: Download MLflow artifacts
      uses: actions/download-artifact@v2
      with:
        name: mlflow-artifacts
        path: mlruns/
        
    - name: Deploy model (simulation)
      run: |
        echo "Model would be deployed here in production environment"
